name:                four-lambs
version:             0.1.0.0
github:              "diegospd/four-lambs"
license:             BSD3
author:              "Diego Murillo"
maintainer:          "diego.albarran@nubank.com.br"
copyright:           "2020 Diego Murillo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/four-lambs#readme>

dependencies:
- base >= 4.7 && < 5
- text
- turtle

library:
  source-dirs: src

executables:
  four-lambs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - four-lambs

tests:
  four-lambs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - four-lambs
